In [28]:
import numpy as np
import pandas as pd
from scipy import stats

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
zp, ks

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [10]:
#найдем средние значения по выборкам
zp_mean=np.mean(zp)
ks_mean=np.mean(ks)
zp_ks_mean=np.mean(zp*ks)
zp_mean, ks_mean, zp_ks_mean

(101.4, 709.9, 81141.7)

In [13]:
#найдем ковариацию по формуле cov=m(xy)-m(x)*m(y)
cov1=zp_ks_mean-zp_mean*ks_mean
cov1

9157.839999999997

In [22]:
#найдем ковариацию функцией
cov2=np.cov(zp, ks, ddof=1)
cov2

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [26]:
#найдем коэф-т пирсона r(xy)=cov(xy)/str(x)*str(y)
zp_std=np.std(zp, ddof=0)
ks_std=np.std(ks, ddof=0)
r=cov1/(zp_std*ks_std)
zp_std, ks_std, r


(59.115480206118605, 174.55340157098058, 0.8874900920739158)

In [27]:
#найдем коэф-т пирсона функцией
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])